#!/bin/bash

# Copyright (C) 2013 Alan Orth
# https://github.com/alanorth/hpc_infrastructure_scripts/
#
# Copyright (C) 2014 Microway, Inc. All rights reserved.
# Modified to support generic resources (accelerators) and other SLURM flags.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

#
# interactive: Obtain interactive shell with slurm allocation
#
# Basically simulates:
#
#    salloc -n1 srun --x11 --pty bash

# defaults
DEF_NUM_CPUS=1
DEF_PARTITION=interactive
DEF_JOB_NAME=${USER}-interactive

######

function help() {
    echo
    echo -e "Obtain an interactive shell on a compute node (via SLURM)."
    echo
    echo -e "Usage: `basename $0` [-c] [-m] [-f] [-g] [-p] [-J] [-r] [-s] [-t]"
    echo
    echo -e "Optional arguments:"
    echo -e "\t -c: number of CPU cores to request (default: $DEF_NUM_CPUS)"
    echo -e "\t -m: number of megabytes of memory to request"

    echo
    echo -e "\t -g: type and number of generic resources - available options:"
    # List available generic resources in SLURM
    srun --gres=help | awk '!/Valid gres/ {print "\t\t",$0}' | sort -u

    echo
    echo -e "\t -f: desired node features (combine features by using the | or & operators)"
    echo -e "\t     Available options:"
    # List available node features in SLURM
    sinfo --format="%f" | awk '!/FEATURES/ {gsub(",", "\n\t\t "); print "\t\t",$0}' | sort -u

    echo
    echo -e "\t -p: partition to run job in (default: $DEF_PARTITION)"
    echo -e "\t -J: job name (default: $DEF_JOB_NAME)"
    echo -e "\t -r: allocate resources from the named reservation"
    echo -e "\t -s: share node with other users (default: yes)"
    echo -e "\t -t: job length (use SLURM time formats)"

    echo
    echo -e "Written by: Alan Orth <a.orth@cgiar.org>"
    echo -e "Microway modifications by: Eliot Eshelman <eliot@microway.com>"
    echo

    exit 0
}

function parse_options() {
    while getopts ":c:m:g:f:p:J:r:s:t:" opt; do
        case $opt in
            c)
                # make sure -c is passed a valid integer
                if ! [[ "$OPTARG" =~ ^[0-9]+$ ]]; then
                    help
                fi

                NUM_CPUS=$OPTARG
                ;;
            m)
                # make sure -m is passed a valid integer
                if ! [[ "$OPTARG" =~ ^[0-9]+$ ]]; then
                    help
                fi

                NUM_MEMORY=$OPTARG
                ;;
            g)
                GRES=$OPTARG
                ;;
            f)
                FEATURES=$OPTARG
                ;;
            p)
                PARTITION=$OPTARG
                ;;
            J)
                JOB_NAME=$OPTARG
                ;;
            r)
                RESERVATION=$OPTARG
                ;;
            s)
                # make sure -s is passed a valid boolean
                OPTARG=${OPTARG:0:1}
                if [[ "$OPTARG" == "0" ]] || [[ "${OPTARG^^}" == "N" ]]; then
                    SHARE_NODE=0
                elif [[ "$OPTARG" == "1" ]] || [[ "${OPTARG^^}" == "Y" ]]; then
                    SHARE_NODE=1
                else
                    help
                fi
                ;;
            t)
                JOB_TIME=$OPTARG
                ;;
            \?|:)
                help
                ;;
        esac
    done
}

function envsetup() {
    # default is to request 1 CPU, unless more are requested
    if [[ $NUM_CPUS -gt $DEF_NUM_CPUS ]]; then
        SALLOC_OPTS="-n $NUM_CPUS"
    else
        SALLOC_OPTS="-n $DEF_NUM_CPUS"
    fi

    # check for memory quantity required (if any)
    if [[ -n "$NUM_MEMORY" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS --mem=$NUM_MEMORY"
    fi

    # check for generic resource requirements (if any)
    if [[ -n "$GRES" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS --gres=$GRES"
    fi

    # check for required features (if any)
    if [[ -n "$FEATURES" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS --constraint=$FEATURES"
    fi

    # see if the user specified a partition
    if [[ -n "$PARTITION" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS -p $PARTITION"
    else
        SALLOC_OPTS="$SALLOC_OPTS -p $DEF_PARTITION"
    fi

    # check for a job name
    if [[ -n "$JOB_NAME" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS -J $JOB_NAME"
    else
        SALLOC_OPTS="$SALLOC_OPTS -J $DEF_JOB_NAME"
    fi

    # check for a specific SLURM reservation
    if [[ -n "$RESERVATION" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS --reservation=$RESERVATION"
    fi

    # set the job to shared or exclusive mode
    if [[ -n "$SHARE_NODE" ]] && [[ "$SHARE_NODE" -eq 0 ]]; then
        SALLOC_OPTS="$SALLOC_OPTS --exclusive"
    else
        SALLOC_OPTS="$SALLOC_OPTS --share"
    fi

    # check for job's time requirements
    if [[ -n "$JOB_TIME" ]]; then
        SALLOC_OPTS="$SALLOC_OPTS --time=$JOB_TIME"
    fi

    # check if we want X11
    if [[ -n "$DISPLAY" ]]; then
        SRUN_OPTS="--x11 --pty"
    else
        SRUN_OPTS="--pty"
    fi

    INTERACTIVE_SHELL=/bin/bash
    SHELL_OPTS="-i -l" # not sure if needed
}

# pass the shell's argument array to the parsing function
parse_options "$@"

# setup the defaults
envsetup


# We may have a pause here if SLURM is getting nodes ready (either by powering
# up nodes that are powered off and/or running long health checks).
echo
echo "Obtaining your interactive shell session..."
echo
echo "Please be patient - if the compute nodes are in power-saving mode,"
echo "it may take 2-3 minutes to start your session..."
echo

salloc $SALLOC_OPTS srun $SRUN_OPTS $INTERACTIVE_SHELL

